# Generated by Django 3.2.23 on 2024-01-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_level', models.CharField(blank=True, max_length=100, verbose_name='上级名')),
                ('path', models.CharField(blank=True, max_length=100, verbose_name='路径')),
                ('redirect', models.CharField(blank=True, max_length=100, verbose_name='重定向')),
                ('meta_title', models.CharField(blank=True, max_length=50, verbose_name='路由名')),
                ('meta_icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('meta_cache', models.CharField(blank=True, max_length=50, verbose_name='cache')),
                ('alway_show', models.CharField(blank=True, max_length=50, verbose_name='alwayShow')),
                ('hideClose', models.CharField(blank=True, max_length=50, verbose_name='是否隐藏')),
                ('component', models.CharField(blank=True, max_length=100, verbose_name='component')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='层级')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='状态')),
            ],
        ),
    ]
