# Generated by Django 3.2.23 on 2024-01-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_auto_20240104_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauth',
            name='m_path',
            field=models.CharField(blank=True, max_length=100, verbose_name='menu路径'),
        ),
    ]
