# Generated by Django 3.2.23 on 2023-12-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job_num',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True, verbose_name='姓名'),
        ),
    ]
