# Generated by Django 3.2.23 on 2023-12-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231229_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('user', '用户'), ('manager', '中心主任'), ('admin', '管理员'), ('SuperAdmin', '超级管理员')], max_length=32, null=True, verbose_name='用户角色'),
        ),
    ]
